### ISSUE TITLE
which file shoud be used ?

### ISSUE THREAD

**Issue by SeekPoint** [ahxt/NeuACF#1]
(.venv) mldl@ub1604:~/ub16_prj/NeuACF/src$ python3.6 ./acf.py ../dataset/amazon/ --mat "U.UIU,I.IUI,U.UITIU,I.ITI,U.UIVIU,I.IVI,U.UICIU,I.ICI" --epochs 40 --last_layer_size 64 --batch_size 1024 --num_of_neg 10 --learn_rate 0.00005 --num_of_layers 2 --mat_select median
/home/mldl/v_pub_py36/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mldl/v_pub_py36/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Usage:
        acf.py [options] <dataset_dir> <dataset>

(.venv) mldl@ub1604:~/ub16_prj/NeuACF/src$ python3.6 ./acf.py ../dataset/amazon/amovie.train.rating --mat "U.UIU,I.IUI,U.UITIU,I.ITI,U.UIVIU,I.IVI,U.UICIU,I.ICI" --epochs 40 --last_layer_size 64 --batch_size 1024 --num_of_neg 10 --learn_rate 0.00005 --num_of_layers 2 --mat_select median
/home/mldl/v_pub_py36/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mldl/v_pub_py36/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Usage:
        acf.py [options] <dataset_dir> <dataset>
(.venv) mldl@ub1604:~/ub16_prj/NeuACF/src$

**Comment by ahxt** [comment]
I have updated the code and you can try the new code, thanks!

**Comment by loveJasmine** [comment]
(.venv) ub16hp@UB16HP:~/ub16_prj/NeuACF/src$ python3.6 acf.py ../dataset/amazon/ amovie --mat "U.UIU,I.IUI,U.UITIU,I.ITI,U.UIVIU,I.IVI,U.UICIU,I.ICI" --epochs 40 --last_layer_size 64 --batch_size 1024 --num_of_neg 10 --learn_rate 0.00005 --num_of_layers 2 --mat_select median
# --mat_select median
# --merge attention
# --num_of_neg 10
# --last_layer_size 64
# --epochs 40
# --mat U.UIU,I.IUI,U.UITIU,I.ITI,U.UIVIU,I.IVI,U.UICIU,I.ICI
# --batch_size 1024
# --learn_rate 0.00005
# --num_of_layers 2
# <dataset_dir> ../dataset/amazon/
# <dataset> amovie
# U_feature1 shape: (6170, 6170)
# I_feature1 shape: (2753, 2753)
Traceback (most recent call last):
  File "acf.py", line 109, in <module>
    U_feature2 = pd.read_csv( U_feature_dir2, sep=",", header=None ).fillna( 0 ).as_matrix()
  File "/home/ub16hp/ub16_prj/NeuACF/.venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/ub16hp/ub16_prj/NeuACF/.venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/ub16hp/ub16_prj/NeuACF/.venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 762, in __init__
    self._make_engine(self.engine)
  File "/home/ub16hp/ub16_prj/NeuACF/.venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 966, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/ub16hp/ub16_prj/NeuACF/.venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 1582, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas/_libs/parsers.c:4209)
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas/_libs/parsers.c:8873)
FileNotFoundError: File b'../dataset/amazon/U.UITIU.pathsim.feature.median' does not exist
(.venv) ub16hp@UB16HP:~/ub16_prj/NeuACF/src$

**Comment by loveJasmine** [comment]
(.venv) ub16hp@UB16HP:~/ub16_prj/NeuACF/src$ python3.6 acf.py ../dataset/amazon/ amovie --mat "U.UIU,I.IUI,U.UICIU,I.ICI" --epochs 40 --last_layer_size 64 --batch_size 1024 --num_of_neg 10 --learn_rate 0.00005 --num_of_layers 2 --mat_select median
# --num_of_neg 10
# --mat U.UIU,I.IUI,U.UICIU,I.ICI
# --batch_size 1024
# --merge attention
# --epochs 40
# --learn_rate 0.00005
# --mat_select median
# --last_layer_size 64
# --num_of_layers 2
# <dataset_dir> ../dataset/amazon/
# <dataset> amovie
# U_feature1 shape: (6170, 6170)
# I_feature1 shape: (2753, 2753)
Traceback (most recent call last):
  File "acf.py", line 109, in <module>
    U_feature2 = pd.read_csv( U_feature_dir2, sep=",", header=None ).fillna( 0 ).as_matrix()
NameError: name 'U_feature_dir2' is not defined
(.venv) ub16hp@UB16HP:~/ub16_prj/NeuACF/src$

**Comment by ahxt** [comment]
Since in this repo I do not upload more Aspect information(for example, T, V information in amazon datatset), and if you want more information, you should compute the similarity matrix first.
you can run this code:
python ./acf.py ../dataset/amazon/ amovie --mat "U.UIU,I.IUI,U.UICIU,I.ICI" --epochs 40 --last_layer_size 64 --batch_size 1024 --num_of_neg 10 --learn_rate 0.00005 --num_of_layers 2 --mat_select median

**Comment by Abigale001** [comment]
Have you dealt with this NameError problem?

> NameError: name 'U_feature_dir2' is not defined

After I run @ahxt 's recommend command, I still have this problem.

**Comment by Shodowelf** [comment]
> Have you dealt with this NameError problem?
> 
> > NameError: name 'U_feature_dir2' is not defined
> 
> After I run @ahxt 's recommend command, I still have this problem.

If you dealt it?
